config/routes.rb
Rails.application.routes.draw do
  root to: "fish#index"
  resources :fish
  devise_for :users
  get "/orders/success", to: "orders#success", as: "success_order"
  post "/orders/webhook", to: "orders#webhook", as: "order"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fish.rb
class Fish < ApplicationRecord
  belongs_to :user
  has_one :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :fish
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fish
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :translate_params, only: [:create, :update]
  before_action :set_fish, only: [:show]
  before_action :set_user_fish, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]

  # GET /fish
  # GET /fish.json
  def index
    @fish = Fish.all
  end

  # GET /fish/1
  # GET /fish/1.json
  def show
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: @fish.name,
        description:@fish.description,
        amount: @fish.price,
        currency: 'aud',
        quantity: 1,
      }],
      payment_intent_data: {
        metadata: {
            user_id: current_user.id,
            fish_id: @fish.id
        }
      },
      success_url: root_url + "orders/success",
      cancel_url: root_url + "fish",
    )

    @session_id = session.id
  end

  # GET /fish/new
  def new
    @fish = Fish.new
  end

  # GET /fish/1/edit
  def edit
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = Fish.new(fish_params)
    @fish.user_id = current_user.id

    respond_to do |format|
      if @fish.save
        format.html { redirect_to @fish, notice: 'Fish was successfully created.' }
        format.json { render :show, status: :created, location: @fish }
      else
        format.html { render :new }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fish/1
  # PATCH/PUT /fish/1.json
  def update
    respond_to do |format|
      if @fish.update(fish_params)
        format.html { redirect_to @fish, notice: 'Fish was successfully updated.' }
        format.json { render :show, status: :ok, location: @fish }
      else
        format.html { render :edit }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy
    @fish.destroy
    respond_to do |format|
      format.html { redirect_to fish_index_url, notice: 'Fish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    def set_user_fish
      @fish = current_user.fish.find_by_id(params[:id])

      if @fish == nil
        redirect_to fish_index_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fish_params
      params.require(:fish).permit(:name, :description, :price, :user_id)
    end

    def translate_params
      params[:fish][:price] = (params[:fish][:price].to_f * 100).to_i
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]
    
    def success

    end

    def webhook
        payment_id = params[:data][:object][:payment_intent]
        payment = Stripe::PaymentIntent.retrieve(payment_id)
        fish_id = payment.metadata.fish_id
        user_id = payment.metadata.user_id
        
        order = Order.new(
            user_id: user_id,
            fish_id: fish_id,
            stripe_id: payment_id
        )

        unless order.save
            puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            puts params
            puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        else
            puts "Order #{order.id} successfully created"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/fish/_form.html.erb
<%= form_with(model: fish, local: true) do |form| %>
  <% if fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% fish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fish/edit.html.erb
<h1>Editing Fish</h1>

<%= render 'form', fish: @fish %>

<%= link_to 'Show', @fish %> |
<%= link_to 'Back', fish_index_path %>

app/views/fish/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fish</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fish.each do |fish| %>
      <tr>
        <td><%= fish.name %></td>
        <td><%= fish.description %></td>
        <td><%= fish.price %></td>
        <td><%= link_to 'Show', fish %></td>
        <td><%= link_to 'Edit', edit_fish_path(fish) if user_signed_in? and fish.user_id == current_user.id %></td>
        <td><%= link_to 'Destroy', fish, method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? and fish.user_id == current_user.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fish', new_fish_path %>

app/views/fish/new.html.erb
<h1>New Fish</h1>

<%= render 'form', fish: @fish %>

<%= link_to 'Back', fish_index_path %>

app/views/fish/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fish.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fish.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fish.price %>
  <% unless @fish.order %>
    <button data-stripe="buy">Buy Now!</button>
  <% end %>
</p>

<p>
  <strong>User:</strong>
  <%= @fish.user.email %>
</p>

<%= link_to 'Edit', edit_fish_path(@fish) %> |
<%= link_to 'Back', fish_index_path %>

<script src="https://js.stripe.com/v3/"></script>

<script>
    document.querySelector("[data-stripe='buy']").addEventListener("click", () => {
        const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public) %>");
        
        stripe.redirectToCheckout({
          sessionId: "<%= @session_id %>"
        });
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FishShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/success.html.erb
Order Success!